  CHK     include/linux/version.h
  CHK     include/generated/utsrelease.h
  HOSTCC  scripts/basic/fixdep
make[1]: “include/generated/mach-types.h”是最新的。
  CC      kernel/bounds.s
  GEN     include/generated/bounds.h
  CC      arch/arm/kernel/asm-offsets.s
  GEN     include/generated/asm-offsets.h
  CALL    scripts/checksyscalls.sh
  HOSTCC  scripts/dtc/checks.o
  HOSTCC  scripts/dtc/data.o
  HOSTCC  scripts/dtc/dtc-lexer.lex.o
  HOSTCC  scripts/dtc/dtc-parser.tab.o
  HOSTCC  scripts/dtc/dtc.o
  HOSTCC  scripts/dtc/flattree.o
  HOSTCC  scripts/dtc/fstree.o
  HOSTCC  scripts/dtc/livetree.o
  HOSTCC  scripts/dtc/srcpos.o
  HOSTCC  scripts/dtc/treesource.o
  HOSTCC  scripts/dtc/util.o
  HOSTLD  scripts/dtc/dtc
  HOSTCC  scripts/genksyms/genksyms.o
  HOSTCC  scripts/genksyms/lex.lex.o
  HOSTCC  scripts/genksyms/parse.tab.o
  HOSTLD  scripts/genksyms/genksyms
  CC      scripts/mod/empty.o
  HOSTCC  scripts/mod/mk_elfconfig
  MKELF   scripts/mod/elfconfig.h
  HOSTCC  scripts/mod/file2alias.o
  HOSTCC  scripts/mod/modpost.o
  HOSTCC  scripts/mod/sumversion.o
  HOSTLD  scripts/mod/modpost
  HOSTCC  scripts/kallsyms
  HOSTCC  scripts/conmakehash
  CC      init/main.o
  CHK     include/generated/compile.h
  CC      init/version.o
  CC      init/do_mounts.o
  CC      init/do_mounts_rd.o
  LD      init/mounts.o
  CC      init/noinitramfs.o
  CC      init/calibrate.o
  LD      init/built-in.o
  LD      usr/built-in.o
  CC      arch/arm/vfp/vfpmodule.o
  AS      arch/arm/vfp/entry.o
  AS      arch/arm/vfp/vfphw.o
  CC      arch/arm/vfp/vfpsingle.o
  CC      arch/arm/vfp/vfpdouble.o
  LD      arch/arm/vfp/vfp.o
  LD      arch/arm/vfp/built-in.o
  CC      arch/arm/kernel/elf.o
  AS      arch/arm/kernel/entry-armv.o
  AS      arch/arm/kernel/entry-common.o
  CC      arch/arm/kernel/irq.o
  CC      arch/arm/kernel/opcodes.o
  CC      arch/arm/kernel/process.o
  CC      arch/arm/kernel/ptrace.o
  CC      arch/arm/kernel/return_address.o
  CC      arch/arm/kernel/sched_clock.o
  CC      arch/arm/kernel/setup.o
  CC      arch/arm/kernel/signal.o
  CC      arch/arm/kernel/stacktrace.o
  CC      arch/arm/kernel/sys_arm.o
  CC      arch/arm/kernel/time.o
  CC      arch/arm/kernel/traps.o
  CC      arch/arm/kernel/cpuidle.o
  CC      arch/arm/kernel/armksyms.o
  CC      arch/arm/kernel/module.o
  AS      arch/arm/kernel/sleep.o
  CC      arch/arm/kernel/suspend.o
  CC      arch/arm/kernel/smp.o
  CC      arch/arm/kernel/smp_tlb.o
  CC      arch/arm/kernel/smp_scu.o
  CC      arch/arm/kernel/smp_twd.o
  CC      arch/arm/kernel/devtree.o
  CC      arch/arm/kernel/swp_emulate.o
  CC      arch/arm/kernel/pmu.o
  CC      arch/arm/kernel/topology.o
  CC      arch/arm/kernel/io.o
  LD      arch/arm/kernel/built-in.o
  AS      arch/arm/kernel/head.o
  CC      arch/arm/kernel/init_task.o
  LDS     arch/arm/kernel/vmlinux.lds
  CC      arch/arm/mm/dma-mapping.o
  CC      arch/arm/mm/extable.o
  CC      arch/arm/mm/fault.o
  CC      arch/arm/mm/init.o
  CC      arch/arm/mm/iomap.o
  CC      arch/arm/mm/fault-armv.o
  CC      arch/arm/mm/flush.o
  CC      arch/arm/mm/idmap.o
  CC      arch/arm/mm/ioremap.o
  CC      arch/arm/mm/mmap.o
  CC      arch/arm/mm/pgd.o
  CC      arch/arm/mm/mmu.o
  CC      arch/arm/mm/vmregion.o
  CC      arch/arm/mm/proc-syms.o
  CC      arch/arm/mm/alignment.o
  AS      arch/arm/mm/abort-ev7.o
  AS      arch/arm/mm/pabort-v7.o
  AS      arch/arm/mm/cache-v7.o
  CC      arch/arm/mm/copypage-v6.o
  CC      arch/arm/mm/context.o
  AS      arch/arm/mm/tlb-v7.o
  AS      arch/arm/mm/proc-v7.o
  LD      arch/arm/mm/built-in.o
  CC      arch/arm/common/gic.o
  LD      arch/arm/common/built-in.o
  LD      arch/arm/net/built-in.o
  CC      arch/arm/mach-sun7i/clock/clock.o
  CC      arch/arm/mach-sun7i/clock/ccm.o
  CC      arch/arm/mach-sun7i/clock/mod_clk.o
  CC      arch/arm/mach-sun7i/clock/sys_clk.o
  CC      arch/arm/mach-sun7i/clock/pll_cfg.o
  CC      arch/arm/mach-sun7i/clock/ccu_dbg.o
  CC      arch/arm/mach-sun7i/clock/ccu_sysfs.o
  LD      arch/arm/mach-sun7i/clock/built-in.o
  CC      arch/arm/mach-sun7i/cpu-freq/cpu-freq.o
  CC      arch/arm/mach-sun7i/cpu-freq/cpu-freq-table.o
  LD      arch/arm/mach-sun7i/cpu-freq/built-in.o
  CC      arch/arm/mach-sun7i/dma/dma.o
  CC      arch/arm/mach-sun7i/dma/dma_interface.o
  CC      arch/arm/mach-sun7i/dma/dma_csp.o
  CC      arch/arm/mach-sun7i/dma/dma_core.o
  LD      arch/arm/mach-sun7i/dma/built-in.o
  CC      arch/arm/mach-sun7i/pm/pm.o
  CC      arch/arm/mach-sun7i/pm/standby/common.o
  CC      arch/arm/mach-sun7i/pm/standby/standby.o
  CC      arch/arm/mach-sun7i/pm/standby/standby_clock.o
  CC      arch/arm/mach-sun7i/pm/standby/standby_ir.o
  CC      arch/arm/mach-sun7i/pm/standby/standby_key.o
  CC      arch/arm/mach-sun7i/pm/standby/standby_power.o
  CC      arch/arm/mach-sun7i/pm/standby/standby_tmr.o
  CC      arch/arm/mach-sun7i/pm/standby/standby_twi.o
  CC      arch/arm/mach-sun7i/pm/standby/standby_usb.o
  AS      arch/arm/mach-sun7i/pm/standby/standby_delay.o
  CC      arch/arm/mach-sun7i/pm/standby/dram.o
  CC      arch/arm/mach-sun7i/pm/standby/dram_init.o
  CC      arch/arm/mach-sun7i/pm/standby/pm_debug.o
  AS      arch/arm/mach-sun7i/pm/standby/mem_delay.o
  AS      arch/arm/mach-sun7i/pm/standby/mem_mmu_pc_asm.o
  CC      arch/arm/mach-sun7i/pm/standby/mem_serial.o
  CC      arch/arm/mach-sun7i/pm/standby/mem_printk.o
  CC      arch/arm/mach-sun7i/pm/standby/mem_divlibc.o
  CC      arch/arm/mach-sun7i/pm/standby/mem_int.o
  CC      arch/arm/mach-sun7i/pm/standby/mem_timing.o
  AS      arch/arm/mach-sun7i/pm/standby/mem_divlib.o
  LD      arch/arm/mach-sun7i/pm/standby/standby.elf
  OBJCOPY arch/arm/mach-sun7i/pm/standby/standby.bin
  AS      arch/arm/mach-sun7i/pm/standby.o
  CC      arch/arm/mach-sun7i/pm/mem_tmr.o
  CC      arch/arm/mach-sun7i/pm/mem_timing.o
  CC      arch/arm/mach-sun7i/pm/mem_divlibc.o
  LD      arch/arm/mach-sun7i/pm/built-in.o
  CC      arch/arm/mach-sun7i/board-em6057e.o
  CC      arch/arm/mach-sun7i/platsmp.o
  AS      arch/arm/mach-sun7i/headsmp.o
  CC      arch/arm/mach-sun7i/hotplug.o
  CC      arch/arm/mach-sun7i/localtimer.o
  LD      arch/arm/mach-sun7i/built-in.o
  CC      arch/arm/plat-sunxi/sys_config.o
  CC      arch/arm/plat-sunxi/core.o
  CC      arch/arm/plat-sunxi/soc-detect.o
  CC      arch/arm/plat-sunxi/script.o
  CC      arch/arm/plat-sunxi/clocksrc.o
  CC      arch/arm/plat-sunxi/devices.o
  LD      arch/arm/plat-sunxi/built-in.o
  CC      kernel/fork.o
  CC      kernel/exec_domain.o
  CC      kernel/panic.o
  CC      kernel/printk.o
  CC      kernel/cpu.o
  CC      kernel/exit.o
  CC      kernel/itimer.o
  TIMEC   kernel/timeconst.h
  CC      kernel/time.o
  CC      kernel/softirq.o
  CC      kernel/resource.o
  CC      kernel/sysctl.o
  CC      kernel/sysctl_binary.o
  CC      kernel/capability.o
  CC      kernel/ptrace.o
  CC      kernel/timer.o
  CC      kernel/user.o
  CC      kernel/signal.o
  CC      kernel/sys.o
  CC      kernel/kmod.o
  CC      kernel/workqueue.o
  CC      kernel/pid.o
  CC      kernel/rcupdate.o
  CC      kernel/extable.o
  CC      kernel/params.o
  CC      kernel/posix-timers.o
  CC      kernel/kthread.o
  CC      kernel/wait.o
  CC      kernel/kfifo.o
  CC      kernel/sys_ni.o
  CC      kernel/posix-cpu-timers.o
  CC      kernel/mutex.o
  CC      kernel/hrtimer.o
  CC      kernel/rwsem.o
  CC      kernel/nsproxy.o
  CC      kernel/srcu.o
  CC      kernel/semaphore.o
  CC      kernel/notifier.o
  CC      kernel/ksysfs.o
  CC      kernel/cred.o
  CC      kernel/async.o
  CC      kernel/range.o
  CC      kernel/groups.o
  CC      kernel/irq/irqdesc.o
  CC      kernel/irq/handle.o
  CC      kernel/irq/manage.o
  CC      kernel/irq/spurious.o
  CC      kernel/irq/resend.o
  CC      kernel/irq/chip.o
  CC      kernel/irq/dummychip.o
  CC      kernel/irq/devres.o
  CC      kernel/irq/autoprobe.o
  CC      kernel/irq/irqdomain.o
  CC      kernel/irq/proc.o
  CC      kernel/irq/pm.o
  LD      kernel/irq/built-in.o
  CC      kernel/power/qos.o
  CC      kernel/power/main.o
  CC      kernel/power/console.o
  CC      kernel/power/process.o
  CC      kernel/power/suspend.o
  LD      kernel/power/built-in.o
  CC      kernel/sched/core.o
  CC      kernel/sched/clock.o
  CC      kernel/sched/idle_task.o
  CC      kernel/sched/fair.o
  CC      kernel/sched/rt.o
  CC      kernel/sched/stop_task.o
  CC      kernel/sched/cpupri.o
  LD      kernel/sched/built-in.o
  CC      kernel/time/timekeeping.o
  CC      kernel/time/ntp.o
  CC      kernel/time/clocksource.o
  CC      kernel/time/jiffies.o
  CC      kernel/time/timer_list.o
  CC      kernel/time/timecompare.o
  CC      kernel/time/timeconv.o
  CC      kernel/time/posix-clock.o
  CC      kernel/time/alarmtimer.o
  CC      kernel/time/clockevents.o
  CC      kernel/time/tick-common.o
  CC      kernel/time/tick-broadcast.o
  CC      kernel/time/tick-oneshot.o
  CC      kernel/time/tick-sched.o
  LD      kernel/time/built-in.o
  CC      kernel/freezer.o
  CC      kernel/futex.o
  CC      kernel/rtmutex.o
  CC      kernel/smp.o
  CC      kernel/spinlock.o
  CC      kernel/uid16.o
  CC      kernel/module.o
  CC      kernel/kallsyms.o
  CC      kernel/stop_machine.o
  CC      kernel/rcutree.o
  CC      kernel/utsname_sysctl.o
  CC      kernel/elfcore.o
  CC      kernel/cpu_pm.o
  LD      kernel/built-in.o
  CC      mm/filemap.o
  CC      mm/mempool.o
  CC      mm/oom_kill.o
  CC      mm/fadvise.o
  CC      mm/maccess.o
  CC      mm/page_alloc.o
  CC      mm/page-writeback.o
  CC      mm/readahead.o
  CC      mm/swap.o
  CC      mm/truncate.o
  CC      mm/vmscan.o
  CC      mm/shmem.o
  CC      mm/prio_tree.o
  CC      mm/util.o
  CC      mm/mmzone.o
  CC      mm/vmstat.o
  CC      mm/backing-dev.o
  CC      mm/page_isolation.o
  CC      mm/mm_init.o
  CC      mm/mmu_context.o
  CC      mm/percpu.o
  CC      mm/fremap.o
  CC      mm/highmem.o
  CC      mm/madvise.o
  CC      mm/memory.o
  CC      mm/mincore.o
  CC      mm/mlock.o
  CC      mm/mmap.o
  CC      mm/mprotect.o
  CC      mm/mremap.o
  CC      mm/msync.o
  CC      mm/rmap.o
  CC      mm/vmalloc.o
  CC      mm/pagewalk.o
  CC      mm/pgtable-generic.o
  CC      mm/process_vm_access.o
  CC      mm/init-mm.o
  CC      mm/bootmem.o
  CC      mm/memblock.o
  CC      mm/bounce.o
  CC      mm/dmapool.o
  CC      mm/ksm.o
  CC      mm/slub.o
  LD      mm/built-in.o
  CC      fs/open.o
  CC      fs/read_write.o
  CC      fs/file_table.o
  CC      fs/super.o
  CC      fs/char_dev.o
  CC      fs/stat.o
  CC      fs/exec.o
  CC      fs/pipe.o
  CC      fs/namei.o
  CC      fs/fcntl.o
  CC      fs/ioctl.o
  CC      fs/readdir.o
  CC      fs/select.o
  CC      fs/fifo.o
  CC      fs/dcache.o
  CC      fs/inode.o
  CC      fs/attr.o
  CC      fs/bad_inode.o
  CC      fs/file.o
  CC      fs/filesystems.o
  CC      fs/namespace.o
  CC      fs/seq_file.o
  CC      fs/xattr.o
  CC      fs/libfs.o
  CC      fs/fs-writeback.o
  CC      fs/pnode.o
  CC      fs/drop_caches.o
  CC      fs/splice.o
  CC      fs/sync.o
  CC      fs/utimes.o
  CC      fs/stack.o
  CC      fs/fs_struct.o
  CC      fs/statfs.o
  CC      fs/buffer.o
  CC      fs/bio.o
  CC      fs/block_dev.o
  CC      fs/direct-io.o
  CC      fs/mpage.o
  CC      fs/ioprio.o
  CC      fs/proc_namespace.o
  CC      fs/devpts/inode.o
  LD      fs/devpts/devpts.o
  LD      fs/devpts/built-in.o
  LD      fs/exofs/built-in.o
  LD      fs/ext4/built-in.o
  LD      fs/fat/built-in.o
  LD      fs/jbd2/built-in.o
  CC      fs/lockd/clntlock.o
  CC      fs/lockd/clntproc.o
  CC      fs/lockd/clntxdr.o
  CC      fs/lockd/host.o
  CC      fs/lockd/svc.o
  CC      fs/lockd/svclock.o
  CC      fs/lockd/svcshare.o
  CC      fs/lockd/svcproc.o
  CC      fs/lockd/svcsubs.o
  CC      fs/lockd/mon.o
  CC      fs/lockd/xdr.o
  CC      fs/lockd/grace.o
  CC      fs/lockd/clnt4xdr.o
  CC      fs/lockd/xdr4.o
  CC      fs/lockd/svc4proc.o
  LD      fs/lockd/lockd.o
  LD      fs/lockd/built-in.o
  CC      fs/nfs/client.o
  CC      fs/nfs/dir.o
  CC      fs/nfs/file.o
  CC      fs/nfs/getroot.o
  CC      fs/nfs/inode.o
  CC      fs/nfs/super.o
  CC      fs/nfs/nfs2xdr.o
  CC      fs/nfs/direct.o
  CC      fs/nfs/pagelist.o
  CC      fs/nfs/proc.o
  CC      fs/nfs/read.o
  CC      fs/nfs/symlink.o
  CC      fs/nfs/unlink.o
  CC      fs/nfs/write.o
  CC      fs/nfs/namespace.o
  CC      fs/nfs/mount_clnt.o
  CC      fs/nfs/dns_resolve.o
  CC      fs/nfs/cache_lib.o
  CC      fs/nfs/nfsroot.o
  CC      fs/nfs/nfs3proc.o
  CC      fs/nfs/nfs3xdr.o
  CC      fs/nfs/sysctl.o
  LD      fs/nfs/nfs.o
  LD      fs/nfs/built-in.o
  LD      fs/nfs_common/built-in.o
  CC      fs/nls/nls_base.o
  LD      fs/nls/built-in.o
  CC      fs/notify/fsnotify.o
  CC      fs/notify/notification.o
  CC      fs/notify/group.o
  CC      fs/notify/inode_mark.o
  CC      fs/notify/mark.o
  CC      fs/notify/vfsmount_mark.o
  CC      fs/notify/dnotify/dnotify.o
  LD      fs/notify/dnotify/built-in.o
  LD      fs/notify/fanotify/built-in.o
  CC      fs/notify/inotify/inotify_fsnotify.o
  CC      fs/notify/inotify/inotify_user.o
  LD      fs/notify/inotify/built-in.o
  LD      fs/notify/built-in.o
  LD      fs/ntfs/built-in.o
  CC      fs/proc/mmu.o
  CC      fs/proc/task_mmu.o
  CC      fs/proc/inode.o
  CC      fs/proc/root.o
  CC      fs/proc/base.o
  CC      fs/proc/generic.o
  CC      fs/proc/array.o
  CC      fs/proc/proc_tty.o
  CC      fs/proc/cmdline.o
  CC      fs/proc/consoles.o
  CC      fs/proc/cpuinfo.o
  CC      fs/proc/devices.o
  CC      fs/proc/interrupts.o
  CC      fs/proc/loadavg.o
  CC      fs/proc/meminfo.o
  CC      fs/proc/stat.o
  CC      fs/proc/uptime.o
  CC      fs/proc/version.o
  CC      fs/proc/softirqs.o
  CC      fs/proc/namespaces.o
  CC      fs/proc/proc_sysctl.o
  CC      fs/proc/proc_net.o
  CC      fs/proc/kmsg.o
  CC      fs/proc/page.o
  LD      fs/proc/proc.o
  LD      fs/proc/built-in.o
  LD      fs/quota/built-in.o
  CC      fs/ramfs/inode.o
  CC      fs/ramfs/file-mmu.o
  LD      fs/ramfs/ramfs.o
  LD      fs/ramfs/built-in.o
  CC      fs/squashfs/block.o
  CC      fs/squashfs/cache.o
  CC      fs/squashfs/dir.o
  CC      fs/squashfs/export.o
  CC      fs/squashfs/file.o
  CC      fs/squashfs/fragment.o
  CC      fs/squashfs/id.o
  CC      fs/squashfs/inode.o
  CC      fs/squashfs/namei.o
  CC      fs/squashfs/super.o
  CC      fs/squashfs/symlink.o
  CC      fs/squashfs/decompressor.o
  CC      fs/squashfs/lzo_wrapper.o
  CC      fs/squashfs/zlib_wrapper.o
  LD      fs/squashfs/squashfs.o
  LD      fs/squashfs/built-in.o
  CC      fs/sysfs/inode.o
  CC      fs/sysfs/file.o
  CC      fs/sysfs/dir.o
  CC      fs/sysfs/symlink.o
  CC      fs/sysfs/mount.o
  CC      fs/sysfs/bin.o
  CC      fs/sysfs/group.o
  LD      fs/sysfs/built-in.o
  CC      fs/ubifs/shrinker.o
  CC      fs/ubifs/journal.o
  CC      fs/ubifs/file.o
  CC      fs/ubifs/dir.o
  CC      fs/ubifs/super.o
  CC      fs/ubifs/sb.o
  CC      fs/ubifs/io.o
  CC      fs/ubifs/tnc.o
  CC      fs/ubifs/master.o
  CC      fs/ubifs/scan.o
  CC      fs/ubifs/replay.o
  CC      fs/ubifs/log.o
  CC      fs/ubifs/commit.o
  CC      fs/ubifs/gc.o
  CC      fs/ubifs/orphan.o
  CC      fs/ubifs/budget.o
  CC      fs/ubifs/find.o
  CC      fs/ubifs/tnc_commit.o
  CC      fs/ubifs/compress.o
  CC      fs/ubifs/lpt.o
  CC      fs/ubifs/lprops.o
  CC      fs/ubifs/recovery.o
  CC      fs/ubifs/ioctl.o
  CC      fs/ubifs/lpt_commit.o
  CC      fs/ubifs/tnc_misc.o
  CC      fs/ubifs/xattr.o
  CC      fs/ubifs/debug.o
  LD      fs/ubifs/ubifs.o
  LD      fs/ubifs/built-in.o
  CC      fs/eventpoll.o
  CC      fs/anon_inodes.o
  CC      fs/signalfd.o
  CC      fs/timerfd.o
  CC      fs/eventfd.o
  CC      fs/aio.o
  CC      fs/locks.o
  CC      fs/binfmt_script.o
  CC      fs/binfmt_elf.o
  LD      fs/built-in.o
  CC      ipc/util.o
  CC      ipc/msgutil.o
  CC      ipc/msg.o
  CC      ipc/sem.o
  CC      ipc/shm.o
  CC      ipc/ipcns_notifier.o
  CC      ipc/syscall.o
  CC      ipc/ipc_sysctl.o
  LD      ipc/built-in.o
  CC      security/commoncap.o
  CC      security/min_addr.o
  LD      security/built-in.o
  CC      crypto/api.o
  CC      crypto/cipher.o
  CC      crypto/compress.o
  CC      crypto/algapi.o
  CC      crypto/scatterwalk.o
  CC      crypto/proc.o
  CC      crypto/ablkcipher.o
  CC      crypto/blkcipher.o
  CC      crypto/ahash.o
  CC      crypto/shash.o
  CC      crypto/algboss.o
  CC      crypto/testmgr.o
  LD      crypto/crypto.o
  CC      crypto/crypto_wq.o
  LD      crypto/crypto_algapi.o
  CC      crypto/aead.o
  LD      crypto/crypto_blkcipher.o
  CC      crypto/chainiv.o
  CC      crypto/eseqiv.o
  LD      crypto/crypto_hash.o
  CC      crypto/pcompress.o
  LD      crypto/cryptomgr.o
  CC      crypto/deflate.o
  CC      crypto/zlib.o
  CC      crypto/lzo.o
  CC      crypto/rng.o
  CC      crypto/krng.o
  LD      crypto/built-in.o
  CC      block/elevator.o
  CC      block/blk-core.o
  CC      block/blk-tag.o
  CC      block/blk-sysfs.o
  CC      block/blk-flush.o
  CC      block/blk-settings.o
  CC      block/blk-ioc.o
  CC      block/blk-map.o
  CC      block/blk-exec.o
  CC      block/blk-merge.o
  CC      block/blk-softirq.o
  CC      block/blk-timeout.o
  CC      block/blk-iopoll.o
  CC      block/blk-lib.o
  CC      block/ioctl.o
  CC      block/genhd.o
  CC      block/scsi_ioctl.o
  CC      block/partition-generic.o
  CC      block/partitions/check.o
  CC      block/partitions/msdos.o
  LD      block/partitions/built-in.o
  CC      block/noop-iosched.o
  LD      block/built-in.o
  CC      drivers/amba/bus.o
  LD      drivers/amba/built-in.o
  LD      drivers/auxdisplay/built-in.o
  CC      drivers/base/core.o
  CC      drivers/base/bus.o
  CC      drivers/base/dd.o
  CC      drivers/base/syscore.o
  CC      drivers/base/driver.o
  CC      drivers/base/class.o
  CC      drivers/base/platform.o
  CC      drivers/base/cpu.o
  CC      drivers/base/firmware.o
  CC      drivers/base/init.o
  CC      drivers/base/map.o
  CC      drivers/base/devres.o
  CC      drivers/base/attribute_container.o
  CC      drivers/base/transport_class.o
  CC      drivers/base/topology.o
  CC      drivers/base/devtmpfs.o
  CC      drivers/base/power/sysfs.o
  CC      drivers/base/power/generic_ops.o
  CC      drivers/base/power/common.o
  CC      drivers/base/power/qos.o
  CC      drivers/base/power/main.o
  CC      drivers/base/power/wakeup.o
  CC      drivers/base/power/runtime.o
  CC      drivers/base/power/clock_ops.o
  LD      drivers/base/power/built-in.o
  CC      drivers/base/dma-mapping.o
  CC      drivers/base/dma-coherent.o
  CC      drivers/base/dma-buf.o
  CC      drivers/base/firmware_class.o
  CC      drivers/base/module.o
  LD      drivers/base/built-in.o
  CC      drivers/block/brd.o
  LD      drivers/block/built-in.o
  LD      drivers/cdrom/built-in.o
  CC      drivers/char/mem.o
  CC      drivers/char/random.o
  CC      drivers/char/misc.o
  CC      drivers/char/sunxi_g2d/g2d_driver.o
  CC      drivers/char/sunxi_g2d/g2d.o
  CC      drivers/char/sunxi_g2d/g2d_bsp.o
  LD      drivers/char/sunxi_g2d/g2d_23.o
  LD      drivers/char/sunxi_g2d/built-in.o
  LD      drivers/char/built-in.o
  CC      drivers/clk/clkdev.o
  LD      drivers/clk/built-in.o
  LD      drivers/clocksource/built-in.o
  CC      drivers/cpufreq/cpufreq.o
  CC      drivers/cpufreq/cpufreq_performance.o
  CC      drivers/cpufreq/cpufreq_ondemand.o
  CC      drivers/cpufreq/freq_table.o
  LD      drivers/cpufreq/built-in.o
  CC      drivers/cpuidle/cpuidle.o
  CC      drivers/cpuidle/driver.o
  CC      drivers/cpuidle/governor.o
  CC      drivers/cpuidle/sysfs.o
  CC      drivers/cpuidle/governors/ladder.o
  CC      drivers/cpuidle/governors/menu.o
  LD      drivers/cpuidle/governors/built-in.o
  LD      drivers/cpuidle/built-in.o
  LD      drivers/crypto/built-in.o
  LD      drivers/firewire/built-in.o
  LD      drivers/firmware/built-in.o
  CC      drivers/gpio/gpiolib.o
  CC      drivers/gpio/devres.o
  CC      drivers/gpio/gpio-sunxi.o
  LD      drivers/gpio/built-in.o
  LD      drivers/gpu/drm/i2c/built-in.o
  LD      drivers/gpu/drm/mali/built-in.o
  LD      drivers/gpu/drm/built-in.o
  LD      drivers/gpu/ion/built-in.o
  LD      drivers/gpu/mali/built-in.o
  LD      drivers/gpu/mali/mali/built-in.o
  LD      drivers/gpu/mali/ump/built-in.o
  LD      drivers/gpu/stub/built-in.o
  LD      drivers/gpu/vga/built-in.o
  LD      drivers/gpu/built-in.o
  LD      drivers/hid/built-in.o
  LD      drivers/hid/usbhid/built-in.o
  LD      drivers/hsi/clients/built-in.o
  LD      drivers/hsi/built-in.o
  CC      drivers/i2c/i2c-boardinfo.o
  CC      drivers/i2c/i2c-core.o
  LD      drivers/i2c/algos/built-in.o
  CC      drivers/i2c/busses/i2c-sunxi.o
  LD      drivers/i2c/busses/built-in.o
  LD      drivers/i2c/muxes/built-in.o
  LD      drivers/i2c/built-in.o
  LD      drivers/idle/built-in.o
  LD      drivers/ieee802154/built-in.o
  CC      drivers/input/input.o
  CC      drivers/input/input-compat.o
  CC      drivers/input/input-mt.o
  CC      drivers/input/ff-core.o
  LD      drivers/input/input-core.o
  CC      drivers/input/mousedev.o
  CC      drivers/input/evdev.o
  CC      drivers/input/touchscreen/sun4i-ts.o
  LD      drivers/input/touchscreen/built-in.o
  LD      drivers/input/built-in.o
  LD      drivers/leds/built-in.o
  LD      drivers/lguest/built-in.o
  LD      drivers/macintosh/built-in.o
  LD      drivers/media/audio/built-in.o
  LD      drivers/media/common/tuners/built-in.o
  LD      drivers/media/common/built-in.o
  LD      drivers/media/radio/built-in.o
  LD      drivers/media/rc/keymaps/built-in.o
  LD      drivers/media/rc/built-in.o
  CC      drivers/media/video/v4l2-dev.o
  CC      drivers/media/video/v4l2-ioctl.o
  CC      drivers/media/video/v4l2-device.o
  CC      drivers/media/video/v4l2-fh.o
  CC      drivers/media/video/v4l2-event.o
  CC      drivers/media/video/v4l2-ctrls.o
  CC      drivers/media/video/v4l2-subdev.o
  LD      drivers/media/video/videodev.o
  CC      drivers/media/video/v4l2-int-device.o
  CC      drivers/media/video/v4l2-common.o
  CC      drivers/media/video/videobuf-core.o
  CC      drivers/media/video/videobuf-dma-contig.o
  LD      drivers/media/video/davinci/built-in.o
  CC      drivers/media/video/sunxi_tvd/drv_tvd.o
  CC      drivers/media/video/sunxi_tvd/bsp_tvd.o
  LD      drivers/media/video/sunxi_tvd/tvd.o
  LD      drivers/media/video/sunxi_tvd/built-in.o
  LD      drivers/media/video/built-in.o
  LD      drivers/media/built-in.o
  LD      drivers/mfd/built-in.o
  LD      drivers/misc/carma/built-in.o
  LD      drivers/misc/cb710/built-in.o
  LD      drivers/misc/eeprom/built-in.o
  LD      drivers/misc/lis3lv02d/built-in.o
  LD      drivers/misc/ti-st/built-in.o
  CC      drivers/misc/em-decrypt.o
  LD      drivers/misc/built-in.o
  CC      drivers/mmc/card/block.o
  CC      drivers/mmc/card/queue.o
  LD      drivers/mmc/card/mmc_block.o
  LD      drivers/mmc/card/built-in.o
  CC      drivers/mmc/core/core.o
  CC      drivers/mmc/core/bus.o
  CC      drivers/mmc/core/host.o
  CC      drivers/mmc/core/mmc.o
  CC      drivers/mmc/core/mmc_ops.o
  CC      drivers/mmc/core/sd.o
  CC      drivers/mmc/core/sd_ops.o
  CC      drivers/mmc/core/sdio.o
  CC      drivers/mmc/core/sdio_ops.o
  CC      drivers/mmc/core/sdio_bus.o
  CC      drivers/mmc/core/sdio_cis.o
  CC      drivers/mmc/core/sdio_io.o
  CC      drivers/mmc/core/sdio_irq.o
  CC      drivers/mmc/core/quirks.o
  CC      drivers/mmc/core/cd-gpio.o
  LD      drivers/mmc/core/mmc_core.o
  LD      drivers/mmc/core/built-in.o
  CC      drivers/mmc/host/sunxi-mci.o
  LD      drivers/mmc/host/built-in.o
  CC      drivers/mmc/mmc-pm/mmc_pm.o
  CC      drivers/mmc/mmc-pm/mmc_pm_swl_n20.o
  CC      drivers/mmc/mmc-pm/mmc_pm_usi_bm01a.o
  CC      drivers/mmc/mmc-pm/mmc_pm_apm6xxx.o
  CC      drivers/mmc/mmc-pm/mmc_pm_swb_b23.o
  CC      drivers/mmc/mmc-pm/mmc_pm_hw_mw269x.o
  CC      drivers/mmc/mmc-pm/mmc_pm_bcm40181.o
  CC      drivers/mmc/mmc-pm/mmc_pm_bcm40183.o
  CC      drivers/mmc/mmc-pm/mmc_pm_rtl8723as.o
  CC      drivers/mmc/mmc-pm/mmc_pm_rtl8189es.o
  LD      drivers/mmc/mmc-pm/mmc_power.o
  LD      drivers/mmc/mmc-pm/built-in.o
  LD      drivers/mmc/sunxi-host/built-in.o
  LD      drivers/mmc/built-in.o
  CC      drivers/mtd/mtdcore.o
  CC      drivers/mtd/mtdsuper.o
  CC      drivers/mtd/mtdconcat.o
  CC      drivers/mtd/mtdpart.o
  LD      drivers/mtd/mtd.o
  CC      drivers/mtd/cmdlinepart.o
  CC      drivers/mtd/mtdchar.o
  CC      drivers/mtd/mtd_blkdevs.o
  CC      drivers/mtd/blockrom.o
  CC      drivers/mtd/chips/chipreg.o
  LD      drivers/mtd/chips/built-in.o
  LD      drivers/mtd/devices/built-in.o
  LD      drivers/mtd/lpddr/built-in.o
  LD      drivers/mtd/maps/built-in.o
  CC      drivers/mtd/nand/nand_base.o
  CC      drivers/mtd/nand/nand_bbt.o
  LD      drivers/mtd/nand/nand.o
  CC      drivers/mtd/nand/nand_ecc.o
  CC      drivers/mtd/nand/nand_ids.o
  CC      drivers/mtd/nand/sunxi-nand/main.o
  CC      drivers/mtd/nand/sunxi-nand/nfc.o
  CC      drivers/mtd/nand/sunxi-nand/dma.o
  CC      drivers/mtd/nand/sunxi-nand/nand_id.o
  CC      drivers/mtd/nand/sunxi-nand/nand1k.o
  LD      drivers/mtd/nand/sunxi-nand/sunxi_nand.o
  LD      drivers/mtd/nand/sunxi-nand/built-in.o
  LD      drivers/mtd/nand/built-in.o
  LD      drivers/mtd/onenand/built-in.o
  LD      drivers/mtd/tests/built-in.o
  CC      drivers/mtd/ubi/vtbl.o
  CC      drivers/mtd/ubi/vmt.o
  CC      drivers/mtd/ubi/upd.o
  CC      drivers/mtd/ubi/build.o
  CC      drivers/mtd/ubi/cdev.o
  CC      drivers/mtd/ubi/kapi.o
  CC      drivers/mtd/ubi/eba.o
  CC      drivers/mtd/ubi/io.o
  CC      drivers/mtd/ubi/wl.o
  CC      drivers/mtd/ubi/attach.o
  CC      drivers/mtd/ubi/misc.o
  CC      drivers/mtd/ubi/debug.o
  LD      drivers/mtd/ubi/ubi.o
  LD      drivers/mtd/ubi/built-in.o
  LD      drivers/mtd/built-in.o
  CC      drivers/net/mii.o
  CC      drivers/net/Space.o
  CC      drivers/net/loopback.o
  CC      drivers/net/can/dev.o
  LD      drivers/net/can/can-dev.o
  LD      drivers/net/can/softing/built-in.o
  LD      drivers/net/can/usb/built-in.o
  CC      drivers/net/can/sunxi_can.o
  LD      drivers/net/can/built-in.o
  CC      drivers/net/ethernet/allwinner/emac/sunxi_emac.o
  LD      drivers/net/ethernet/allwinner/emac/built-in.o
  LD      drivers/net/ethernet/allwinner/built-in.o
  LD      drivers/net/ethernet/microchip/built-in.o
  LD      drivers/net/ethernet/built-in.o
  CC      drivers/net/phy/phy.o
  CC      drivers/net/phy/phy_device.o
  CC      drivers/net/phy/mdio_bus.o
  LD      drivers/net/phy/libphy.o
  CC      drivers/net/phy/smsc.o
  LD      drivers/net/phy/built-in.o
  LD      drivers/net/ppp/built-in.o
  LD      drivers/net/slip/built-in.o
  LD      drivers/net/wireless/built-in.o
  LD      drivers/net/wireless/bcmdhd-legacy/built-in.o
  LD      drivers/net/built-in.o
  LD      drivers/nfc/built-in.o
  CC      drivers/of/base.o
  CC      drivers/of/fdt.o
  CC      drivers/of/address.o
  CC      drivers/of/irq.o
  CC      drivers/of/device.o
  CC      drivers/of/platform.o
  CC      drivers/of/gpio.o
  CC      drivers/of/of_i2c.o
  CC      drivers/of/of_net.o
  CC      drivers/of/of_spi.o
  CC      drivers/of/of_mdio.o
  CC      drivers/of/of_mtd.o
  LD      drivers/of/built-in.o
  LD      drivers/pinctrl/built-in.o
  LD      drivers/platform/built-in.o
  CC      drivers/power/power_supply_core.o
  CC      drivers/power/power_supply_sysfs.o
  LD      drivers/power/power_supply.o
  CC      drivers/power/axp152.o
  LD      drivers/power/built-in.o
  CC      drivers/regulator/core.o
  CC      drivers/regulator/dummy.o
  CC      drivers/regulator/fixed-helper.o
  CC      drivers/regulator/of_regulator.o
  LD      drivers/regulator/built-in.o
  CC      drivers/rtc/rtc-lib.o
  CC      drivers/rtc/hctosys.o
  CC      drivers/rtc/class.o
  CC      drivers/rtc/interface.o
  CC      drivers/rtc/rtc-dev.o
  LD      drivers/rtc/rtc-core.o
  CC      drivers/rtc/rtc-pcf8563.o
  LD      drivers/rtc/built-in.o
  CC      drivers/scsi/scsi.o
  CC      drivers/scsi/hosts.o
  CC      drivers/scsi/scsi_ioctl.o
  CC      drivers/scsi/constants.o
  CC      drivers/scsi/scsicam.o
  CC      drivers/scsi/scsi_error.o
  CC      drivers/scsi/scsi_lib.o
  CC      drivers/scsi/scsi_lib_dma.o
  CC      drivers/scsi/scsi_scan.o
  CC      drivers/scsi/scsi_sysfs.o
  CC      drivers/scsi/scsi_devinfo.o
  CC      drivers/scsi/scsi_sysctl.o
  CC      drivers/scsi/scsi_trace.o
  CC      drivers/scsi/scsi_pm.o
  CC      drivers/scsi/sd.o
  LD      drivers/scsi/scsi_mod.o
  LD      drivers/scsi/arm/built-in.o
  LD      drivers/scsi/sd_mod.o
  LD      drivers/scsi/built-in.o
  CC      drivers/spi/spi.o
  CC      drivers/spi/em6057e-stm32-spi.o
  CC      drivers/spi/spi-sun7i.o
  LD      drivers/spi/built-in.o
  CC      drivers/tty/tty_io.o
  CC      drivers/tty/n_tty.o
  CC      drivers/tty/tty_ioctl.o
  CC      drivers/tty/tty_ldisc.o
  CC      drivers/tty/tty_buffer.o
  CC      drivers/tty/tty_port.o
  CC      drivers/tty/tty_mutex.o
  CC      drivers/tty/pty.o
  LD      drivers/tty/ipwireless/built-in.o
  CC      drivers/tty/serial/serial_core.o
  CC      drivers/tty/serial/8250/8250.o
  CC      drivers/tty/serial/8250/8250_early.o
  CC      drivers/tty/serial/8250/8250_sunxi.o
  LD      drivers/tty/serial/8250/built-in.o
  LD      drivers/tty/serial/built-in.o
  CC      drivers/tty/vt/vt_ioctl.o
  CC      drivers/tty/vt/vc_screen.o
  CC      drivers/tty/vt/selection.o
  CC      drivers/tty/vt/keyboard.o
  CC      drivers/tty/vt/consolemap.o
  CONMK   drivers/tty/vt/consolemap_deftbl.c
  CC      drivers/tty/vt/consolemap_deftbl.o
  CC      drivers/tty/vt/vt.o
  SHIPPED drivers/tty/vt/defkeymap.c
  CC      drivers/tty/vt/defkeymap.o
  LD      drivers/tty/vt/built-in.o
  LD      drivers/tty/built-in.o
  CC      drivers/usb/core/usb.o
  CC      drivers/usb/core/hub.o
  CC      drivers/usb/core/hcd.o
  CC      drivers/usb/core/urb.o
  CC      drivers/usb/core/message.o
  CC      drivers/usb/core/driver.o
  CC      drivers/usb/core/config.o
  CC      drivers/usb/core/file.o
  CC      drivers/usb/core/buffer.o
  CC      drivers/usb/core/sysfs.o
  CC      drivers/usb/core/endpoint.o
  CC      drivers/usb/core/devio.o
  CC      drivers/usb/core/notify.o
  CC      drivers/usb/core/generic.o
  CC      drivers/usb/core/quirks.o
  CC      drivers/usb/core/devices.o
  CC      drivers/usb/core/inode.o
  LD      drivers/usb/core/usbcore.o
  LD      drivers/usb/core/built-in.o
  LD      drivers/usb/gadget/built-in.o
  CC      drivers/usb/host/ehci-hcd.o
  CC      drivers/usb/host/ohci-hcd.o
  CC      drivers/usb/host/sw_hci_sunxi.o
  LD      drivers/usb/host/built-in.o
  LD      drivers/usb/misc/built-in.o
  CC      drivers/usb/serial/usb-serial.o
  CC      drivers/usb/serial/generic.o
  CC      drivers/usb/serial/bus.o
  LD      drivers/usb/serial/usbserial.o
  CC      drivers/usb/serial/option.o
  CC      drivers/usb/serial/usb_wwan.o
  LD      drivers/usb/serial/built-in.o
  CC      drivers/usb/storage/scsiglue.o
  CC      drivers/usb/storage/protocol.o
  CC      drivers/usb/storage/transport.o
  CC      drivers/usb/storage/usb.o
  CC      drivers/usb/storage/initializers.o
  CC      drivers/usb/storage/sierra_ms.o
  CC      drivers/usb/storage/option_ms.o
  CC      drivers/usb/storage/usual-tables.o
  LD      drivers/usb/storage/usb-storage.o
  LD      drivers/usb/storage/built-in.o
  CC      drivers/usb/usb-common.o
  LD      drivers/usb/built-in.o
  CC      drivers/video/fb_notify.o
  CC      drivers/video/fbmem.o
  CC      drivers/video/fbmon.o
  CC      drivers/video/fbcmap.o
  CC      drivers/video/fbsysfs.o
  CC      drivers/video/modedb.o
  CC      drivers/video/fbcvt.o
  LD      drivers/video/fb.o
  CC      drivers/video/backlight/backlight.o
  CC      drivers/video/backlight/generic_bl.o
  LD      drivers/video/backlight/built-in.o
  CC      drivers/video/console/dummycon.o
  LD      drivers/video/console/built-in.o
  LD      drivers/video/omap2/displays/built-in.o
  LD      drivers/video/omap2/built-in.o
  CC      drivers/video/sunxi/disp/dev_disp.o
  CC      drivers/video/sunxi/disp/dev_fb.o
  CC      drivers/video/sunxi/disp/OSAL_Clock.o
  CC      drivers/video/sunxi/disp/OSAL_Pin.o
  CC      drivers/video/sunxi/disp/de_be.o
  CC      drivers/video/sunxi/disp/de_fe.o
  CC      drivers/video/sunxi/disp/de_hwc.o
  CC      drivers/video/sunxi/disp/de_layer.o
  CC      drivers/video/sunxi/disp/de_lcdc.o
  CC      drivers/video/sunxi/disp/de_tvec.o
  CC      drivers/video/sunxi/disp/disp_clk.o
  CC      drivers/video/sunxi/disp/disp_combined.o
  CC      drivers/video/sunxi/disp/disp_de.o
  CC      drivers/video/sunxi/disp/disp_display.o
  CC      drivers/video/sunxi/disp/disp_event.o
  CC      drivers/video/sunxi/disp/disp_hdmi.o
  CC      drivers/video/sunxi/disp/disp_hwc.o
  CC      drivers/video/sunxi/disp/disp_layer.o
  CC      drivers/video/sunxi/disp/disp_lcd.o
  CC      drivers/video/sunxi/disp/disp_scaler.o
  CC      drivers/video/sunxi/disp/disp_sprite.o
  CC      drivers/video/sunxi/disp/disp_tv.o
  CC      drivers/video/sunxi/disp/disp_vga.o
  CC      drivers/video/sunxi/disp/disp_video.o
  CC      drivers/video/sunxi/disp/de_iep.o
  CC      drivers/video/sunxi/disp/disp_iep.o
  LD      drivers/video/sunxi/disp/disp.o
  LD      drivers/video/sunxi/disp/built-in.o
  CC      drivers/video/sunxi/lcd/lcd_panel_cfg_generic.o
  CC      drivers/video/sunxi/lcd/dev_lcd.o
  CC      drivers/video/sunxi/lcd/lcd0_panel_cfg.o
  CC      drivers/video/sunxi/lcd/lcd1_panel_cfg.o
  LD      drivers/video/sunxi/lcd/lcd.o
  LD      drivers/video/sunxi/lcd/built-in.o
  CC      drivers/video/splashfb.o
  CC      drivers/video/cfbfillrect.o
  CC      drivers/video/cfbcopyarea.o
  CC      drivers/video/cfbimgblt.o
  LD      drivers/video/built-in.o
  LD      drivers/built-in.o
  LD      sound/built-in.o
  LD      firmware/built-in.o
  CC      net/socket.o
  LD      net/802/built-in.o
  CC      net/can/raw.o
  CC      net/can/af_can.o
  CC      net/can/proc.o
  LD      net/can/can.o
  LD      net/can/can-raw.o
  LD      net/can/built-in.o
  CC      net/core/sock.o
  CC      net/core/request_sock.o
  CC      net/core/skbuff.o
  CC      net/core/iovec.o
  CC      net/core/datagram.o
  CC      net/core/stream.o
  CC      net/core/scm.o
  CC      net/core/gen_stats.o
  CC      net/core/gen_estimator.o
  CC      net/core/net_namespace.o
  CC      net/core/secure_seq.o
  CC      net/core/flow_dissector.o
  CC      net/core/sysctl_net_core.o
  CC      net/core/dev.o
  CC      net/core/ethtool.o
  CC      net/core/dev_addr_lists.o
  CC      net/core/dst.o
  CC      net/core/netevent.o
  CC      net/core/neighbour.o
  CC      net/core/rtnetlink.o
  CC      net/core/utils.o
  CC      net/core/link_watch.o
  CC      net/core/filter.o
  CC      net/core/sock_diag.o
  CC      net/core/flow.o
  CC      net/core/net-sysfs.o
  LD      net/core/built-in.o
  CC      net/ethernet/eth.o
  LD      net/ethernet/built-in.o
  CC      net/ipv4/route.o
  CC      net/ipv4/inetpeer.o
  CC      net/ipv4/protocol.o
  CC      net/ipv4/ip_input.o
  CC      net/ipv4/ip_fragment.o
  CC      net/ipv4/ip_forward.o
  CC      net/ipv4/ip_options.o
  CC      net/ipv4/ip_output.o
  CC      net/ipv4/ip_sockglue.o
  CC      net/ipv4/inet_hashtables.o
  CC      net/ipv4/inet_timewait_sock.o
  CC      net/ipv4/inet_connection_sock.o
  CC      net/ipv4/tcp.o
  CC      net/ipv4/tcp_input.o
  CC      net/ipv4/tcp_output.o
  CC      net/ipv4/tcp_timer.o
  CC      net/ipv4/tcp_ipv4.o
  CC      net/ipv4/tcp_minisocks.o
  CC      net/ipv4/tcp_cong.o
  CC      net/ipv4/datagram.o
  CC      net/ipv4/raw.o
  CC      net/ipv4/udp.o
  CC      net/ipv4/udplite.o
  CC      net/ipv4/arp.o
  CC      net/ipv4/icmp.o
  CC      net/ipv4/devinet.o
  CC      net/ipv4/af_inet.o
  CC      net/ipv4/igmp.o
  CC      net/ipv4/fib_frontend.o
  CC      net/ipv4/fib_semantics.o
  CC      net/ipv4/fib_trie.o
  CC      net/ipv4/inet_fragment.o
  CC      net/ipv4/ping.o
  CC      net/ipv4/sysctl_net_ipv4.o
  CC      net/ipv4/sysfs_net_ipv4.o
  CC      net/ipv4/proc.o
  CC      net/ipv4/ipconfig.o
  CC      net/ipv4/tcp_cubic.o
  CC      net/ipv4/xfrm4_policy.o
  CC      net/ipv4/xfrm4_state.o
  CC      net/ipv4/xfrm4_input.o
  CC      net/ipv4/xfrm4_output.o
  LD      net/ipv4/built-in.o
  CC      net/ipv6/addrconf_core.o
  CC      net/ipv6/exthdrs_core.o
  LD      net/ipv6/built-in.o
  LD      net/key/built-in.o
  CC      net/netlink/af_netlink.o
  CC      net/netlink/genetlink.o
  LD      net/netlink/built-in.o
  LD      net/packet/built-in.o
  LD      net/rfkill/built-in.o
  CC      net/sched/sch_generic.o
  CC      net/sched/sch_mq.o
  LD      net/sched/built-in.o
  CC      net/sunrpc/clnt.o
  CC      net/sunrpc/xprt.o
  CC      net/sunrpc/socklib.o
  CC      net/sunrpc/xprtsock.o
  CC      net/sunrpc/sched.o
  CC      net/sunrpc/auth.o
  CC      net/sunrpc/auth_null.o
  CC      net/sunrpc/auth_unix.o
  CC      net/sunrpc/auth_generic.o
  CC      net/sunrpc/svc.o
  CC      net/sunrpc/svcsock.o
  CC      net/sunrpc/svcauth.o
  CC      net/sunrpc/svcauth_unix.o
  CC      net/sunrpc/addr.o
  CC      net/sunrpc/rpcb_clnt.o
  CC      net/sunrpc/timer.o
  CC      net/sunrpc/xdr.o
  CC      net/sunrpc/sunrpc_syms.o
  CC      net/sunrpc/cache.o
  CC      net/sunrpc/rpc_pipe.o
  CC      net/sunrpc/svc_xprt.o
  CC      net/sunrpc/stats.o
  CC      net/sunrpc/sysctl.o
  LD      net/sunrpc/sunrpc.o
  LD      net/sunrpc/built-in.o
  CC      net/unix/af_unix.o
  CC      net/unix/garbage.o
  CC      net/unix/sysctl_net_unix.o
  LD      net/unix/unix.o
  LD      net/unix/built-in.o
  CC      net/wireless/wext-core.o
  CC      net/wireless/wext-proc.o
  CC      net/wireless/wext-priv.o
  LD      net/wireless/built-in.o
  CC      net/xfrm/xfrm_policy.o
  CC      net/xfrm/xfrm_state.o
  CC      net/xfrm/xfrm_hash.o
  CC      net/xfrm/xfrm_input.o
  CC      net/xfrm/xfrm_output.o
  CC      net/xfrm/xfrm_algo.o
  CC      net/xfrm/xfrm_sysctl.o
  CC      net/xfrm/xfrm_replay.o
  LD      net/xfrm/built-in.o
  CC      net/sysctl_net.o
  LD      net/built-in.o
  LD      arch/arm/lib/built-in.o
  AS      arch/arm/lib/ashldi3.o
  AS      arch/arm/lib/ashrdi3.o
  AS      arch/arm/lib/backtrace.o
  AS      arch/arm/lib/call_with_stack.o
  AS      arch/arm/lib/changebit.o
  AS      arch/arm/lib/clear_user.o
  AS      arch/arm/lib/clearbit.o
  AS      arch/arm/lib/copy_from_user.o
  AS      arch/arm/lib/copy_page.o
  AS      arch/arm/lib/copy_to_user.o
  AS      arch/arm/lib/csumipv6.o
  AS      arch/arm/lib/csumpartial.o
  AS      arch/arm/lib/csumpartialcopy.o
  AS      arch/arm/lib/csumpartialcopyuser.o
  AS      arch/arm/lib/delay.o
  AS      arch/arm/lib/div64.o
  AS      arch/arm/lib/findbit.o
  AS      arch/arm/lib/getuser.o
  AS      arch/arm/lib/io-readsb.o
  AS      arch/arm/lib/io-readsl.o
  AS      arch/arm/lib/io-readsw-armv4.o
  AS      arch/arm/lib/io-writesb.o
  AS      arch/arm/lib/io-writesl.o
  AS      arch/arm/lib/io-writesw-armv4.o
  AS      arch/arm/lib/lib1funcs.o
  AS      arch/arm/lib/lshrdi3.o
  AS      arch/arm/lib/memchr.o
  AS      arch/arm/lib/memcpy.o
  AS      arch/arm/lib/memmove.o
  AS      arch/arm/lib/memset.o
  AS      arch/arm/lib/memzero.o
  AS      arch/arm/lib/muldi3.o
  AS      arch/arm/lib/putuser.o
  AS      arch/arm/lib/setbit.o
  AS      arch/arm/lib/strchr.o
  AS      arch/arm/lib/strncpy_from_user.o
  AS      arch/arm/lib/strnlen_user.o
  AS      arch/arm/lib/strrchr.o
  AS      arch/arm/lib/testchangebit.o
  AS      arch/arm/lib/testclearbit.o
  AS      arch/arm/lib/testsetbit.o
  AS      arch/arm/lib/ucmpdi2.o
  AR      arch/arm/lib/lib.a
  CC      lib/bcd.o
  CC      lib/div64.o
  CC      lib/sort.o
  CC      lib/parser.o
  CC      lib/halfmd4.o
  CC      lib/debug_locks.o
  CC      lib/random32.o
  CC      lib/bust_spinlocks.o
  CC      lib/hexdump.o
  CC      lib/kasprintf.o
  CC      lib/bitmap.o
  CC      lib/scatterlist.o
  CC      lib/string_helpers.o
  CC      lib/gcd.o
  CC      lib/lcm.o
  CC      lib/list_sort.o
  CC      lib/uuid.o
  CC      lib/flex_array.o
  CC      lib/bsearch.o
  CC      lib/find_last_bit.o
  CC      lib/find_next_bit.o
  CC      lib/llist.o
  CC      lib/kstrtox.o
  CC      lib/pci_iomap.o
  CC      lib/iomap_copy.o
  CC      lib/devres.o
  CC      lib/hweight.o
  CC      lib/bitrev.o
  CC      lib/crc16.o
  HOSTCC  lib/gen_crc32table
  GEN     lib/crc32table.h
  CC      lib/crc32.o
  CC      lib/lzo/lzo1x_compress.o
  CC      lib/lzo/lzo1x_decompress_safe.o
  LD      lib/lzo/lzo_compress.o
  LD      lib/lzo/lzo_decompress.o
  LD      lib/lzo/built-in.o
  CC      lib/zlib_deflate/deflate.o
  CC      lib/zlib_deflate/deftree.o
  CC      lib/zlib_deflate/deflate_syms.o
  LD      lib/zlib_deflate/zlib_deflate.o
  LD      lib/zlib_deflate/built-in.o
  CC      lib/zlib_inflate/inffast.o
  CC      lib/zlib_inflate/inflate.o
  CC      lib/zlib_inflate/infutil.o
  CC      lib/zlib_inflate/inftrees.o
  CC      lib/zlib_inflate/inflate_syms.o
  LD      lib/zlib_inflate/zlib_inflate.o
  LD      lib/zlib_inflate/built-in.o
  CC      lib/percpu_counter.o
  CC      lib/nlattr.o
  CC      lib/cpu_rmap.o
  CC      lib/dynamic_queue_limits.o
  LD      lib/built-in.o
  CC      lib/argv_split.o
  CC      lib/bug.o
  CC      lib/cmdline.o
  CC      lib/cpumask.o
  CC      lib/ctype.o
  CC      lib/dec_and_lock.o
  CC      lib/decompress.o
  CC      lib/decompress_inflate.o
  CC      lib/dump_stack.o
  CC      lib/extable.o
  CC      lib/idr.o
  CC      lib/int_sqrt.o
  CC      lib/ioremap.o
  CC      lib/irq_regs.o
  CC      lib/is_single_threaded.o
  CC      lib/klist.o
  CC      lib/kobject.o
  CC      lib/kobject_uevent.o
  CC      lib/md5.o
  CC      lib/plist.o
  CC      lib/prio_heap.o
  CC      lib/prio_tree.o
  CC      lib/proportions.o
  CC      lib/radix-tree.o
  CC      lib/ratelimit.o
  CC      lib/rbtree.o
  CC      lib/reciprocal_div.o
  CC      lib/rwsem-spinlock.o
  CC      lib/sha1.o
  CC      lib/show_mem.o
  CC      lib/string.o
  CC      lib/timerqueue.o
  CC      lib/vsprintf.o
  AR      lib/lib.a
  LD      vmlinux.o
  MODPOST vmlinux.o
  GEN     .version
  CHK     include/generated/compile.h
  UPD     include/generated/compile.h
  CC      init/version.o
  LD      init/built-in.o
  LD      .tmp_vmlinux1
  KSYM    .tmp_kallsyms1.S
  AS      .tmp_kallsyms1.o
  LD      .tmp_vmlinux2
  KSYM    .tmp_kallsyms2.S
  AS      .tmp_kallsyms2.o
  LD      vmlinux
  SYSMAP  System.map
  SYSMAP  .tmp_System.map
  OBJCOPY arch/arm/boot/Image
  Kernel: arch/arm/boot/Image is ready
  AS      arch/arm/boot/compressed/head.o
  LZ4     arch/arm/boot/compressed/piggy.lz4
  AS      arch/arm/boot/compressed/piggy.lz4.o
  CC      arch/arm/boot/compressed/misc.o
  CC      arch/arm/boot/compressed/decompress.o
  CC      arch/arm/boot/compressed/string.o
  SHIPPED arch/arm/boot/compressed/lib1funcs.S
  AS      arch/arm/boot/compressed/lib1funcs.o
  SHIPPED arch/arm/boot/compressed/ashldi3.S
  AS      arch/arm/boot/compressed/ashldi3.o
  LD      arch/arm/boot/compressed/vmlinux
  OBJCOPY arch/arm/boot/zImage
  Kernel: arch/arm/boot/zImage is ready
  UIMAGE  arch/arm/boot/uImage
Image Name:   Linux-3.4.61
Created:      Fri Sep 26 16:04:14 2014
Image Type:   ARM Linux Kernel Image (uncompressed)
Data Size:    2682648 Bytes = 2619.77 kB = 2.56 MB
Load Address: 48000000
Entry Point:  48000000
  Image arch/arm/boot/uImage is ready
